[mypy]
files = src/trading_kernel, tests/trading_kernel, scripts/trading_kernel
explicit_package_bases = True
namespace_packages = True
warn_unused_configs = True

[mypy-asyncpg]
ignore_missing_imports = True

[mypy-ccxt.*]
ignore_missing_imports = True
