import type { components } from "./schema";

const generatedAt = "2026-08-09T08:00:00.000Z";
const baseTime = 1_807_408_800_000;
const evidence = (kind: components["schemas"]["EvidenceRef"]["kind"], identity: string, occurredAtMs = baseTime) => ({ kind, identity, occurred_at_ms: occurredAtMs });
const money = (value: string | null, unit: components["schemas"]["MoneyMetric"]["unit"] = "USDT", unavailableReason: string | null = null) => ({ value, unit, unavailable_reason: unavailableReason });

export const overviewFixture = {
  snapshot_id: "snapshot:overview:e2e",
  generated_at: generatedAt,
  source_watermark: generatedAt,
  freshness: "fresh",
  data: {
    observed_at_ms: baseTime,
    conclusion: { level: "no_action", summary: "系统运行正常，无需 Owner 操作", owner_action: null, evidence: [evidence("fact", "overview:fresh")] },
    account_snapshot: { label: "Latest Admission Snapshot", is_realtime: false, captured_at_ms: baseTime - 60_000, wallet_balance: money("103.5100"), available_margin: money("72.3400") },
    ticket_capacity: 3,
    active_ticket_count: 1,
    active_ticket_ids: ["ticket:active:1"],
    today_net_pnl: money("3.5100"),
    today_net_r: money("0.4800", "R"),
    today_signal_count: 4,
    admitted_signal_count: 1,
    rejected_signal_count: 3,
    execution_incident_count: 0,
    attention_summary: ["一笔活动 Ticket 已受初始保护"],
    evidence: [evidence("fact", "overview:fresh"), evidence("ticket", "ticket:active:1")],
  },
} satisfies components["schemas"]["ApiEnvelope_OwnerOverview_"];

export const rejectedSignal = {
  signal_event_id: "signal:rejected:1",
  exposure_episode_id: "episode:rejected:1",
  strategy_group_id: "SOR-LONG",
  strategy_version_id: "sor-v1",
  event_spec_id: "event:SOR",
  exchange_instrument_id: "BTCUSDT",
  position_side: "long",
  occurred_at_ms: baseTime - 3_600_000,
  expires_at_ms: baseTime,
  admission_decision_id: "decision:rejected:1",
  decision_status: "rejected",
  first_blocker: "gross_stop_risk_capacity_exhausted",
  binding_constraint: "gross_stop_risk_capacity_exhausted",
  ticket_id: null,
  shadow_summary: { shadow_outcome_id: "shadow:1", source_kind: "portfolio_rejection", evaluation_kind: "fixed_horizon_excursion_v1", status: "completed", mfe_r: "1.25", mae_r: "-0.40", first_path: null, first_path_at_ms: null, observed_bar_count: null, spread_bps: null, mark_index_deviation_bps: null, completion_reason: "horizon_complete", observed_through_ms: baseTime, completed_at_ms: baseTime, interpretation: "Observation only; this Shadow Outcome is not execution.", evidence: [evidence("shadow", "shadow:1")] },
  evidence: [evidence("signal", "signal:rejected:1"), evidence("admission", "decision:rejected:1")],
} satisfies components["schemas"]["SignalListItem"];

export const admittedSignal = {
  ...rejectedSignal,
  signal_event_id: "signal:admitted:2",
  exposure_episode_id: "episode:admitted:2",
  admission_decision_id: "decision:admitted:2",
  decision_status: "admitted",
  first_blocker: null,
  binding_constraint: null,
  ticket_id: "ticket:active:1",
  shadow_summary: null,
  evidence: [evidence("signal", "signal:admitted:2"), evidence("admission", "decision:admitted:2")],
} satisfies components["schemas"]["SignalListItem"];

export const signalListFixture = {
  snapshot_id: "snapshot:signals:e2e",
  generated_at: generatedAt,
  source_watermark: generatedAt,
  freshness: "fresh",
  data: { items: [rejectedSignal, admittedSignal], next_cursor: null },
} satisfies components["schemas"]["ApiEnvelope_SignalListPage_"];

export const signalDetailFixture = {
  snapshot_id: "snapshot:signal-detail:e2e",
  generated_at: generatedAt,
  source_watermark: generatedAt,
  freshness: "fresh",
  data: {
    signal: rejectedSignal,
    what_happened: "The persisted AdmissionDecision rejected this Signal; no Ticket was created.",
    why_no_ticket: "gross_stop_risk_capacity_exhausted",
    fact_snapshots: [{ signal_event_id: rejectedSignal.signal_event_id, fact_definition_id: "fact:gross-stop-risk", role: "condition", value: false, satisfied: false, observed_at_ms: baseTime - 3_600_000, valid_until_ms: baseTime, projection_version: 1 }],
    shadow_summary: rejectedSignal.shadow_summary,
    evidence: rejectedSignal.evidence,
  },
} satisfies components["schemas"]["ApiEnvelope_SignalAdmissionDetail_"];

export const activeTrade = {
  ticket_id: "ticket:active:1",
  strategy_group_id: "SOR-LONG",
  event_spec_id: "event:SOR",
  exchange_instrument_id: "BNBUSDT",
  position_side: "long",
  ticket_status: "POSITION_PROTECTED",
  aggregate_status: "POSITION_PROTECTED",
  lifecycle_stage: "protection",
  completed_stage_count: 4,
  total_stage_count: 8,
  issued_at_ms: baseTime - 2_700_000,
  terminal_at_ms: null,
  exit_reason: null,
  exit_reason_unavailable_reason: "ticket_active",
  gross_pnl: money(null, "USDT", "ticket_active"),
  fees: money("-0.1200"),
  funding: money("0.0100"),
  net_pnl: money(null, "USDT", "ticket_active"),
  net_r: money(null, "R", "ticket_active"),
  economics_completeness: null,
  review_id: null,
  review_revision: null,
  attention_items: ["等待退出"],
  evidence: [evidence("ticket", "ticket:active:1")],
} satisfies components["schemas"]["TradeListItem"];

export const terminalTrade = {
  ...activeTrade,
  ticket_id: "ticket:terminal:2",
  strategy_group_id: "MPG-SHORT",
  exchange_instrument_id: "BTCUSDT",
  position_side: "short",
  ticket_status: "TERMINAL",
  aggregate_status: "TERMINAL",
  lifecycle_stage: "review",
  completed_stage_count: 8,
  terminal_at_ms: baseTime,
  exit_reason: "TP1 + Runner Exit",
  exit_reason_unavailable_reason: null,
  gross_pnl: money("3.8000"),
  fees: money("-0.2500"),
  funding: money("-0.0400"),
  net_pnl: money("3.5100"),
  net_r: money("0.4800", "R"),
  economics_completeness: "complete",
  review_id: "review:ticket:terminal:2",
  review_revision: 1,
  attention_items: [],
  evidence: [evidence("ticket", "ticket:terminal:2"), evidence("review", "review:ticket:terminal:2")],
} satisfies components["schemas"]["TradeListItem"];

export const tradeListFixture = {
  snapshot_id: "snapshot:trades:e2e",
  generated_at: generatedAt,
  source_watermark: generatedAt,
  freshness: "fresh",
  data: { items: [activeTrade, terminalTrade], next_cursor: null },
} satisfies components["schemas"]["ApiEnvelope_TradeListPage_"];

const stageKeys: components["schemas"]["LifecycleStageView"]["key"][] = ["signal", "admission", "entry", "protection", "tp_runner", "exit", "reconciliation", "review"];
const stageLabels = ["Signal", "Admission", "Entry", "Protection", "TP / Runner", "Exit", "Reconciliation / Settlement", "Review"];
const activeStages = stageKeys.map((key, index) => ({ key, label: stageLabels[index] ?? key, status: index < 3 ? "complete" as const : index === 3 ? "current" as const : "pending" as const, started_at_ms: index <= 3 ? baseTime - (4 - index) * 600_000 : null, completed_at_ms: index < 3 ? baseTime - (4 - index) * 600_000 + 300_000 : null, duration_ms: index < 3 ? 300_000 : null, summary: key === "protection" ? "InitialStopConfirmed 后持仓受保护" : `${key} stage`, evidence: index <= 3 ? [evidence("event", `event:${key}:active`)] : [] }));

export const tradeCausalityFixture = {
  snapshot_id: "snapshot:causality:e2e",
  generated_at: generatedAt,
  source_watermark: generatedAt,
  freshness: "fresh",
  data: {
    trade: activeTrade,
    price_plan: {
      strategy_timeframe: "1h",
      entry_reference_price: "610.20",
      entry_limit_price: null,
      actual_entry_price: "612.80",
      initial_stop_price: "598.40",
      active_stop_price: "598.40",
      tp1_price: "627.20",
      ticket_quantity: "0.02",
      tp1_target_quantity: "0.01",
      tp1_filled_quantity: "0",
      initial_stop_distance_percent: "-2.349869281045751633986928105",
      tp1_distance_percent: "2.349869281045751633986928105",
      tp1_reward_r: "1",
    },
    current_stage: "protection",
    current_stage_summary: "InitialStopConfirmed 后持仓受保护",
    stages: activeStages,
    annotations: [{ kind: "signal", label: "Signal", occurred_at_ms: baseTime - 2_700_000, price: "610.20", evidence: [evidence("signal", "signal:admitted:2")] }, { kind: "entry", label: "ENTRY", occurred_at_ms: baseTime - 1_800_000, price: "612.80", evidence: [evidence("command", "command:entry:active")] }, { kind: "stop", label: "Initial Stop", occurred_at_ms: baseTime - 900_000, price: "598.40", evidence: [evidence("command", "command:stop:active")] }],
    exit_reason: null,
    raw_events: [{ event_id: "event:initial-stop-confirmed", ticket_id: activeTrade.ticket_id, sequence: 4, event_type: "InitialStopConfirmed", payload: { stop_price: "598.40" }, occurred_at_ms: baseTime - 900_000, stage: "protection", classification: "mapped", evidence: [evidence("event", "event:initial-stop-confirmed")] }],
    raw_commands: [{ command_id: "command:entry:active", ticket_id: activeTrade.ticket_id, command_kind: "ENTRY", generation: 1, status: "accepted", request_payload: { quantity: "0.02" }, result_payload: { order_id: "order:entry:active" }, created_at_ms: baseTime - 1_800_000, completed_at_ms: baseTime - 1_770_000, evidence: [evidence("command", "command:entry:active")] }],
    raw_incidents: [],
    signal_evidence: [evidence("signal", "signal:admitted:2")],
    order_evidence: [evidence("command", "command:entry:active")],
    incident_evidence: [],
    event_evidence: [evidence("event", "event:initial-stop-confirmed")],
    settlement_evidence: [],
    review_evidence: [],
    evidence: [evidence("ticket", activeTrade.ticket_id), evidence("event", "event:initial-stop-confirmed")],
  },
} satisfies components["schemas"]["ApiEnvelope_TradeCausalityDetail_"];

export const candleFixture = {
  snapshot_id: "snapshot:candles:e2e",
  generated_at: generatedAt,
  source_watermark: generatedAt,
  freshness: "fresh",
  data: { candles: Array.from({ length: 48 }, (_, index) => ({ open_time_ms: baseTime - 172_800_000 + index * 3_600_000, close_time_ms: baseTime - 169_200_001 + index * 3_600_000, open: `${600 + index * 0.4}`, high: `${604 + index * 0.4}`, low: `${598 + index * 0.4}`, close: `${602 + index * 0.4}`, volume: `${800 + index * 10}` })) },
} satisfies components["schemas"]["ApiEnvelope_CandleSeries_"];

export const observationCandleFixture = {
  snapshot_id: "snapshot:candles:observation:e2e",
  generated_at: generatedAt,
  source_watermark: generatedAt,
  freshness: "fresh",
  data: {
    candles: Array.from({ length: 24 }, (_, index) => {
      const open = 209.4 + index * 0.12;
      return {
        open_time_ms: baseTime - 21_600_000 + index * 900_000,
        close_time_ms: baseTime - 20_700_001 + index * 900_000,
        open: open.toFixed(2),
        high: (open + 0.35).toFixed(2),
        low: (open - 0.25).toFixed(2),
        close: (open + 0.18).toFixed(2),
        volume: `${800 + index * 10}`,
      };
    }),
  },
} satisfies components["schemas"]["ApiEnvelope_CandleSeries_"];

const completeReviewItem = {
  ticket_id: terminalTrade.ticket_id,
  strategy_group_id: terminalTrade.strategy_group_id,
  exchange_instrument_id: terminalTrade.exchange_instrument_id,
  position_side: terminalTrade.position_side,
  terminal_at_ms: terminalTrade.terminal_at_ms!,
  review: { ticket_id: terminalTrade.ticket_id, review_status: "complete", execution_classification: "complete", economic_summary: { gross_pnl: terminalTrade.gross_pnl, fees: terminalTrade.fees, funding: terminalTrade.funding, net_pnl: terminalTrade.net_pnl, net_r: money("-1.114162711864406779661016949", "R") }, exit_reason: terminalTrade.exit_reason, attention_items: [], sentences: [{ template_id: "execution_complete", text: "执行链完整。ENTRY 后初始保护已确认；退出由 TP1 后 Runner EXIT 触发。", evidence: [evidence("event", "event:terminal:complete"), evidence("review", "review:ticket:terminal:2")] }], final_conclusion: "执行链完整。", evidence: terminalTrade.evidence },
} satisfies components["schemas"]["ReviewCenterItem"];

export const reviewFixture = {
  snapshot_id: "snapshot:review:e2e",
  generated_at: generatedAt,
  source_watermark: generatedAt,
  freshness: "fresh",
  data: { from_ms: baseTime - 30 * 86_400_000, to_ms: baseTime, sample_count: 1, next_cursor: null, items: [completeReviewItem], net_pnl: terminalTrade.net_pnl, net_r: money("-1.114162711864406779661016949", "R"), fees: terminalTrade.fees, funding: terminalTrade.funding, exit_reason_breakdown: [{ label: "deployment_drain:deploy-20260804-8627ae9c:8627ae9ca5430fd9f8b9a76935f685cd36960ccc", ticket_count: 1, evidence: terminalTrade.evidence }], execution_quality_breakdown: [{ label: "complete", ticket_count: 1, evidence: terminalTrade.evidence }], complete_review_count: 1, incomplete_review_count: 0, strategy_group_samples: [{ strategy_group_id: terminalTrade.strategy_group_id, sample_count: 1, evidence_state: "observe_only", evidence: terminalTrade.evidence }], evidence: terminalTrade.evidence },
} satisfies components["schemas"]["ApiEnvelope_ReviewCenterSummary_"];

const strategyVersionFixture = {
  strategy_group_id: "BRF2-001",
  strategy_group_display_name: "BRF2",
  strategy_version_id: "strategy-version:brf2:v3",
  version: 3,
  strategy_version_status: "active",
  is_current: true,
  ticket_count: 4,
  natural_terminal_count: 3,
  confirmed_natural_review_count: 2,
  pending_natural_review_count: 1,
  controlled_exit_count: 1,
  tp1_reached_count: 1,
  tp1_not_reached_count: 2,
  win_count: 1,
  loss_count: 1,
  net_pnl: money("8.12"),
  net_r: money("0.81", "R"),
  observation_count: 0,
  completed_observation_count: 0,
  unavailable_observation_count: 0,
  tp1_first_count: 0,
  initial_stop_first_count: 0,
  opening_range_failure_count: 0,
  ambiguous_observation_count: 0,
  time_stop_count: 0,
  session_exit_count: 0,
  median_mfe_r: null,
  median_mae_r: null,
  median_spread_bps: null,
  evidence: [evidence("fact", "strategy-version:brf2:v3")],
  product_events: [{
    event_spec_id: "event_spec:BRF2-001:v3:BRF2-SHORT-1H",
    event_id: "BRF2-SHORT-1H",
    position_side: "short",
    timeframe: "1h",
    venue_id: "binance-usdm",
    product_family: "crypto_perpetual",
    runtime_profile_id: "tiny-live-v1",
    owner_policy_id: "policy-main",
    active_universe_version_id: "universe:brf2:v1",
    active_exchange_instrument_ids: ["binance-usdm:BTCUSDT:perpetual"],
    warming_universe_version_id: null,
    warming_exchange_instrument_ids: [],
  }],
} satisfies components["schemas"]["StrategyVersionSummary"];

const tradfiStrategyVersionFixture = {
  strategy_group_id: "SOR-US-EQ-PERP-001",
  strategy_group_display_name: "SOR US Equity Perpetual",
  strategy_version_id: "sgv:SOR-US-EQ-PERP-001:v1",
  version: 1,
  strategy_version_status: "active",
  is_current: true,
  ticket_count: 0,
  natural_terminal_count: 0,
  confirmed_natural_review_count: 0,
  pending_natural_review_count: 0,
  controlled_exit_count: 0,
  tp1_reached_count: 0,
  tp1_not_reached_count: 0,
  win_count: 0,
  loss_count: 0,
  net_pnl: money(null, "USDT", "no_confirmed_natural_review"),
  net_r: money(null, "R", "no_confirmed_natural_review"),
  observation_count: 7,
  completed_observation_count: 6,
  unavailable_observation_count: 1,
  tp1_first_count: 2,
  initial_stop_first_count: 2,
  opening_range_failure_count: 1,
  ambiguous_observation_count: 1,
  time_stop_count: 0,
  session_exit_count: 0,
  median_mfe_r: "0.82",
  median_mae_r: "0.64",
  median_spread_bps: "2.35",
  evidence: [evidence("fact", "sgv:SOR-US-EQ-PERP-001:v1")],
  product_events: [
    {
      event_spec_id: "event_spec:SOR-US-EQ-PERP-001:SOR-US-LONG-15M:v1",
      event_id: "SOR-US-LONG-15M",
      position_side: "long",
      timeframe: "15m",
      venue_id: "binance-usdm",
      product_family: "tradfi_equity_perpetual",
      runtime_profile_id: "tradfi-equity-usdm-v1",
      owner_policy_id: "policy-main",
      active_universe_version_id: null,
      active_exchange_instrument_ids: [],
      warming_universe_version_id: null,
      warming_exchange_instrument_ids: [],
    },
    {
      event_spec_id: "event_spec:SOR-US-EQ-PERP-001:SOR-US-SHORT-15M:v1",
      event_id: "SOR-US-SHORT-15M",
      position_side: "short",
      timeframe: "15m",
      venue_id: "binance-usdm",
      product_family: "tradfi_equity_perpetual",
      runtime_profile_id: "tradfi-equity-usdm-v1",
      owner_policy_id: "policy-main",
      active_universe_version_id: null,
      active_exchange_instrument_ids: [],
      warming_universe_version_id: null,
      warming_exchange_instrument_ids: [],
    },
  ],
} satisfies components["schemas"]["StrategyVersionSummary"];

const strategyObservationRowFixture = {
  shadow_outcome_id: "shadow:strategy:sor-us:1",
  signal_event_id: "signal:sor-us:1",
  ticket_id: null,
  strategy_version_id: "sgv:SOR-US-EQ-PERP-001:v1",
  exchange_instrument_id: "binance-usdm:AAPLUSDT:perpetual",
  position_side: "long",
  occurred_at_ms: baseTime - 3_600_000,
  horizon_start_ms: baseTime - 3_600_000,
  horizon_end_ms: baseTime + 3_600_000,
  status: "completed",
  entry_reference_price: "210.12",
  initial_stop_price: "207.84",
  take_profit_price: "212.40",
  opening_range_boundary_price: "209.60",
  session_exit_deadline_ms: baseTime + 3_600_000,
  best_bid_price: "210.10",
  best_ask_price: "210.12",
  best_bid_quantity: "18",
  best_ask_quantity: "15",
  spread_bps: "0.95",
  mark_index_deviation_bps: "1.10",
  max_favorable_price: "212.80",
  max_adverse_price: "209.70",
  mfe_r: "1.18",
  mae_r: "0.18",
  completion_reason: "sor_path_observed",
  first_path: "tp1_first",
  first_path_at_ms: baseTime - 900_000,
  observed_bar_count: 3,
  completed_at_ms: baseTime,
  annotations: [
    { kind: "signal", occurred_at_ms: baseTime - 3_600_000, price: "210.12", label: "OBSERVATION SIGNAL", evidence: [evidence("signal", "signal:sor-us:1")] },
    { kind: "take_profit", occurred_at_ms: baseTime - 900_000, price: "212.40", label: "TP1 OBSERVED", evidence: [evidence("shadow", "shadow:strategy:sor-us:1")] },
  ],
  evidence: [evidence("signal", "signal:sor-us:1"), evidence("shadow", "shadow:strategy:sor-us:1")],
} satisfies components["schemas"]["StrategyObservationListItem"];

export const strategyObservationFixture = {
  snapshot_id: "snapshot:strategy-observations:e2e",
  generated_at: generatedAt,
  source_watermark: generatedAt,
  freshness: "fresh",
  data: { items: [strategyObservationRowFixture], next_cursor: null },
} satisfies components["schemas"]["ApiEnvelope_StrategyObservationListPage_"];

const strategyTicketRowFixture = {
  ticket_id: "ticket:strategy:brf2:tp1",
  strategy_group_id: "BRF2-001",
  event_spec_id: "event:brf2:v3",
  exchange_instrument_id: "BTCUSDT",
  position_side: "short",
  ticket_status: "terminal",
  aggregate_status: "terminal",
  lifecycle_stage: "review",
  issued_at_ms: baseTime - 4_800_000,
  terminal_at_ms: baseTime - 3_600_000,
  review_id: "review:strategy:brf2:tp1",
  review_revision: 1,
  economics_completeness: "complete",
  completed_stage_count: 8,
  total_stage_count: 8,
  exit_reason: "runner_exit",
  exit_reason_unavailable_reason: null,
  gross_pnl: money("9.36"),
  fees: money("0.82"),
  funding: money("-0.42"),
  net_pnl: money("8.12"),
  net_r: money("0.81", "R"),
  attention_items: [],
  evaluation_path: "tp1_reached",
  evidence: [evidence("ticket", "ticket:strategy:brf2:tp1"), evidence("review", "review:strategy:brf2:tp1")],
} satisfies components["schemas"]["StrategyTicketListItem"];

export const strategyFixture = {
  snapshot_id: "snapshot:strategies:e2e",
  generated_at: generatedAt,
  source_watermark: generatedAt,
  freshness: "fresh",
  data: {
    from_ms: baseTime - 30 * 86_400_000,
    to_ms: baseTime,
    view: "current",
    items: [strategyVersionFixture, tradfiStrategyVersionFixture],
    evidence: [...strategyVersionFixture.evidence, ...tradfiStrategyVersionFixture.evidence],
  },
} satisfies components["schemas"]["ApiEnvelope_StrategySummaryPage_"];

export const strategyTicketFixture = {
  snapshot_id: "snapshot:strategy-tickets:e2e",
  generated_at: generatedAt,
  source_watermark: generatedAt,
  freshness: "fresh",
  data: { items: [strategyTicketRowFixture], next_cursor: null },
} satisfies components["schemas"]["ApiEnvelope_StrategyTicketListPage_"];

export const instrumentFixture = {
  snapshot_id: "snapshot:instruments:e2e",
  generated_at: generatedAt,
  source_watermark: generatedAt,
  freshness: "fresh",
  data: {
    candidate_count: 1,
    reference_count: 1,
    unavailable_count: 0,
    regular_session_count: 2,
    source_watermark_ms: baseTime,
    items: [
      {
        exchange_instrument_id: "binance-usdm:AAPLUSDT:perpetual",
        venue_symbol: "AAPLUSDT",
        product_family: "tradfi_equity_perpetual",
        asset_class: "equity",
        contract_type: "TRADIFI_PERPETUAL",
        underlying_type: "EQUITY",
        margin_asset: "USDT",
        entry_session_policy: "regular_only",
        profile_status: "candidate",
        max_entry_spread_bps: "20",
        max_mark_index_deviation_bps: "50",
        product_status: "active",
        session_state: "regular",
        regular_session_open_ms: baseTime - 3_600_000,
        regular_session_close_ms: baseTime + 18_000_000,
        mark_price: "228.12",
        index_price: "228.08",
        funding_rate: "0.0001",
        best_bid: "228.10",
        best_ask: "228.14",
        corporate_event_status: "clear",
        observed_at_ms: baseTime,
        valid_until_ms: baseTime + 900_000,
        source_ref: "binance:fapi:manual-refresh",
        memberships: [{
          strategy_group_id: "SOR-US-EQ-PERP-001",
          strategy_group_display_name: "SOR US Equity Perpetual",
          strategy_version_id: "sgv:SOR-US-EQ-PERP-001:v1",
          event_spec_id: "event_spec:SOR-US-EQ-PERP-001:SOR-US-LONG-15M:v1",
          event_id: "SOR-US-LONG-15M",
          position_side: "long",
          runtime_profile_id: "tradfi-equity-usdm-v1",
          owner_policy_id: "policy-main",
          universe_version_id: "universe:SOR-US-LONG-15M:v1",
          lifecycle_state: "active",
        }],
      },
      {
        exchange_instrument_id: "binance-usdm:QQQUSDT:perpetual",
        venue_symbol: "QQQUSDT",
        product_family: "tradfi_equity_perpetual",
        asset_class: "equity",
        contract_type: "TRADIFI_PERPETUAL",
        underlying_type: "EQUITY",
        margin_asset: "USDT",
        entry_session_policy: "reference_only",
        profile_status: "reference",
        max_entry_spread_bps: null,
        max_mark_index_deviation_bps: null,
        product_status: "active",
        session_state: "regular",
        regular_session_open_ms: baseTime - 3_600_000,
        regular_session_close_ms: baseTime + 18_000_000,
        mark_price: "555.12",
        index_price: "555.08",
        funding_rate: "0.0001",
        best_bid: "555.10",
        best_ask: "555.14",
        corporate_event_status: "clear",
        observed_at_ms: baseTime,
        valid_until_ms: baseTime + 900_000,
        source_ref: "binance:fapi:manual-refresh",
        memberships: [],
      },
    ],
    universes: [{
      strategy_group_id: "SOR-US-EQ-PERP-001",
      strategy_group_display_name: "SOR US Equity Perpetual",
      strategy_version_id: "sgv:SOR-US-EQ-PERP-001:v1",
      event_spec_id: "event_spec:SOR-US-EQ-PERP-001:SOR-US-LONG-15M:v1",
      event_id: "SOR-US-LONG-15M",
      position_side: "long",
      product_family: "tradfi_equity_perpetual",
      runtime_profile_id: "tradfi-equity-usdm-v1",
      owner_policy_id: "policy-main",
      universe_version_id: "universe:SOR-US-LONG-15M:v1",
      lifecycle_state: "active",
      exchange_instrument_ids: ["binance-usdm:AAPLUSDT:perpetual"],
    }],
  },
} satisfies components["schemas"]["ApiEnvelope_InstrumentCenterPage_"];

export const ownerApiFixtures = { overviewFixture, signalListFixture, signalDetailFixture, tradeListFixture, tradeCausalityFixture, candleFixture, observationCandleFixture, reviewFixture, strategyFixture, strategyTicketFixture, strategyObservationFixture, instrumentFixture } as const;
