/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/owner/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Verify JSON credentials and issue only the signed random Session ID.
         */
        post: operations["login_api_owner_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Clear the matching in-memory Session and expire its cookie.
         */
        post: operations["logout_api_owner_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session
         * @description Expose only current authenticated status after cookie verification.
         */
        get: operations["session_api_owner_v1_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/v1/control-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Control Events */
        get: operations["read_control_events_api_owner_v1_control_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/v1/control-operations/{authorization_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Control Operation */
        get: operations["read_control_operation_api_owner_v1_control_operations__authorization_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/v1/controls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Controls */
        get: operations["read_controls_api_owner_v1_controls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/v1/controls/entry/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Global Entry */
        post: operations["pause_global_entry_api_owner_v1_controls_entry_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/v1/controls/entry/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Global Entry */
        post: operations["resume_global_entry_api_owner_v1_controls_entry_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/v1/controls/exposure/flatten-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Flatten Submit */
        post: operations["flatten_submit_api_owner_v1_controls_exposure_flatten_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/v1/controls/exposure/flatten-all/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Flatten Preview */
        post: operations["flatten_preview_api_owner_v1_controls_exposure_flatten_all_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/v1/controls/strategies/{strategy_group_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Strategy */
        post: operations["pause_strategy_api_owner_v1_controls_strategies__strategy_group_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/v1/controls/strategies/{strategy_group_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Strategy */
        post: operations["resume_strategy_api_owner_v1_controls_strategies__strategy_group_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/v1/market/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Candles
         * @description Read public closed candles without opening a PostgreSQL transaction.
         */
        get: operations["candles_api_owner_v1_market_candles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Overview
         * @description Return one internally consistent Owner overview snapshot.
         */
        get: operations["overview_api_owner_v1_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/v1/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Review Center
         * @description Return one deterministic bounded terminal Review Center snapshot.
         */
        get: operations["review_center_api_owner_v1_review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/v1/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Signals
         * @description Return one bounded keyset-paginated Signal page.
         */
        get: operations["signals_api_owner_v1_signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/v1/signals/{signal_event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Signal Detail
         * @description Return exact persisted admission causality for one Signal.
         */
        get: operations["signal_detail_api_owner_v1_signals__signal_event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/v1/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tickets
         * @description Return one bounded keyset-paginated active/terminal Ticket page.
         */
        get: operations["tickets_api_owner_v1_tickets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner/v1/tickets/{ticket_id}/causality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ticket Causality
         * @description Return one exact immutable Ticket causality workbench.
         */
        get: operations["ticket_causality_api_owner_v1_tickets__ticket_id__causality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdmissionAccountSnapshot */
        AdmissionAccountSnapshot: {
            available_margin: components["schemas"]["MoneyMetric"];
            /** Captured At Ms */
            captured_at_ms: number | null;
            /**
             * Is Realtime
             * @default false
             * @constant
             */
            is_realtime: false;
            /**
             * Label
             * @constant
             */
            label: "Latest Admission Snapshot";
            wallet_balance: components["schemas"]["MoneyMetric"];
        };
        /** ApiEnvelope[CandleSeries] */
        ApiEnvelope_CandleSeries_: {
            data: components["schemas"]["CandleSeries"];
            freshness: components["schemas"]["Freshness"];
            /** Generated At */
            generated_at: string;
            /** Snapshot Id */
            snapshot_id: string;
            /** Source Watermark */
            source_watermark: string | null;
        };
        /** ApiEnvelope[OwnerOverview] */
        ApiEnvelope_OwnerOverview_: {
            data: components["schemas"]["OwnerOverview"];
            freshness: components["schemas"]["Freshness"];
            /** Generated At */
            generated_at: string;
            /** Snapshot Id */
            snapshot_id: string;
            /** Source Watermark */
            source_watermark: string | null;
        };
        /** ApiEnvelope[ReviewCenterSummary] */
        ApiEnvelope_ReviewCenterSummary_: {
            data: components["schemas"]["ReviewCenterSummary"];
            freshness: components["schemas"]["Freshness"];
            /** Generated At */
            generated_at: string;
            /** Snapshot Id */
            snapshot_id: string;
            /** Source Watermark */
            source_watermark: string | null;
        };
        /** ApiEnvelope[SignalAdmissionDetail] */
        ApiEnvelope_SignalAdmissionDetail_: {
            data: components["schemas"]["SignalAdmissionDetail"];
            freshness: components["schemas"]["Freshness"];
            /** Generated At */
            generated_at: string;
            /** Snapshot Id */
            snapshot_id: string;
            /** Source Watermark */
            source_watermark: string | null;
        };
        /** ApiEnvelope[SignalListPage] */
        ApiEnvelope_SignalListPage_: {
            data: components["schemas"]["SignalListPage"];
            freshness: components["schemas"]["Freshness"];
            /** Generated At */
            generated_at: string;
            /** Snapshot Id */
            snapshot_id: string;
            /** Source Watermark */
            source_watermark: string | null;
        };
        /** ApiEnvelope[TradeCausalityDetail] */
        ApiEnvelope_TradeCausalityDetail_: {
            data: components["schemas"]["TradeCausalityDetail"];
            freshness: components["schemas"]["Freshness"];
            /** Generated At */
            generated_at: string;
            /** Snapshot Id */
            snapshot_id: string;
            /** Source Watermark */
            source_watermark: string | null;
        };
        /** ApiEnvelope[TradeListPage] */
        ApiEnvelope_TradeListPage_: {
            data: components["schemas"]["TradeListPage"];
            freshness: components["schemas"]["Freshness"];
            /** Generated At */
            generated_at: string;
            /** Snapshot Id */
            snapshot_id: string;
            /** Source Watermark */
            source_watermark: string | null;
        };
        /** CandleSeries */
        CandleSeries: {
            /** Candles */
            candles: components["schemas"]["CandleView"][];
        };
        /** CandleView */
        CandleView: {
            /** Close */
            close: string;
            /** Close Time Ms */
            close_time_ms: number;
            /** High */
            high: string;
            /** Low */
            low: string;
            /** Open */
            open: string;
            /** Open Time Ms */
            open_time_ms: number;
            /** Volume */
            volume: string;
        };
        /** CausalityExitReason */
        CausalityExitReason: {
            /** Code */
            code: string;
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /** Label */
            label: string;
        };
        /** ChartAnnotation */
        ChartAnnotation: {
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /**
             * Kind
             * @enum {string}
             */
            kind: "signal" | "entry" | "stop" | "take_profit" | "exit";
            /** Label */
            label: string;
            /** Occurred At Ms */
            occurred_at_ms: number;
            /** Price */
            price: string;
        };
        /** ControlEventView */
        ControlEventView: {
            /** Authorization Id */
            authorization_id: string;
            /** Created At Ms */
            created_at_ms: number;
            /** Event Id */
            event_id: string;
            /** First Blocker */
            first_blocker?: string | null;
            /** State */
            state: string;
            /** Version */
            version: number;
        };
        /** ControlEventsResponse */
        ControlEventsResponse: {
            /** Items */
            items: components["schemas"]["ControlEventView"][];
        };
        /**
         * ControlOperationState
         * @enum {string}
         */
        ControlOperationState: "validating" | "pending" | "claimed" | "exits_requested" | "exit_in_progress" | "reconciliation_pending" | "settlement_pending" | "review_pending" | "completed" | "blocked" | "needs_intervention";
        /** ControlWriteBody */
        ControlWriteBody: {
            /** Expected Version */
            expected_version: number;
            /** Idempotency Key */
            idempotency_key: string;
            /** Reason */
            reason: string;
            /** Totp Code */
            totp_code?: string | null;
        };
        /** ControlsResponse */
        ControlsResponse: {
            current_operation: components["schemas"]["OwnerControlOperation"] | null;
            /** Events */
            events: components["schemas"]["ControlEventView"][];
            /** Generated At Ms */
            generated_at_ms: number;
            global_entry: components["schemas"]["GlobalEntryView"];
            /** Recent Operations */
            recent_operations: components["schemas"]["OwnerControlOperation"][];
            /** Strategies */
            strategies: components["schemas"]["StrategyControlView"][];
        };
        /** EmptyControlBody */
        EmptyControlBody: Record<string, never>;
        /** EvidenceRef */
        EvidenceRef: {
            /** Identity */
            identity: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "signal" | "admission" | "ticket" | "aggregate" | "event" | "command" | "incident" | "settlement" | "review" | "shadow" | "fact";
            /** Occurred At Ms */
            occurred_at_ms: number;
        };
        /** FlattenBody */
        FlattenBody: {
            /**
             * Confirmation Text
             * @constant
             */
            confirmation_text: "确认平仓全部持仓";
            /** Expected Version */
            expected_version: number;
            /** Idempotency Key */
            idempotency_key: string;
            /** Reason */
            reason: string;
            /** Snapshot Digest */
            snapshot_digest: string;
            /** Totp Code */
            totp_code?: string | null;
        };
        /** FlattenPreview */
        FlattenPreview: {
            /** Account Id */
            account_id: string;
            /** First Blocker */
            first_blocker?: string | null;
            /** Global Entry Enabled */
            global_entry_enabled: boolean;
            /** Owner Policy Version */
            owner_policy_version: number;
            /** Runtime Profile Id */
            runtime_profile_id: string;
            /** Snapshot Digest */
            snapshot_digest: string;
            /** Ticket Ids */
            ticket_ids: string[];
            /** Ticket States */
            ticket_states: {
                [key: string]: string;
            };
            /** Venue Id */
            venue_id: string;
        };
        /**
         * Freshness
         * @enum {string}
         */
        Freshness: "fresh" | "stale" | "unavailable" | "contradictory";
        /** GlobalEntryView */
        GlobalEntryView: {
            /** Active Ticket Count */
            active_ticket_count: number;
            /**
             * Configured State
             * @enum {string}
             */
            configured_state: "enabled" | "paused";
            /**
             * Effective State
             * @enum {string}
             */
            effective_state: "enabled" | "paused";
            /** First Blocker */
            first_blocker?: string | null;
            /** Policy Version */
            policy_version: number;
        };
        /** GlobalMutationResponse */
        GlobalMutationResponse: {
            /**
             * Configured State
             * @enum {string}
             */
            configured_state: "enabled" | "paused";
            /**
             * Effective State
             * @enum {string}
             */
            effective_state: "enabled" | "paused";
            /** Updated At Ms */
            updated_at_ms: number;
            /** Version */
            version: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        JsonValue: unknown;
        /** LifecycleStageView */
        LifecycleStageView: {
            /** Completed At Ms */
            completed_at_ms: number | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /**
             * Key
             * @enum {string}
             */
            key: "signal" | "admission" | "entry" | "protection" | "tp_runner" | "exit" | "reconciliation" | "review";
            /** Label */
            label: string;
            /** Started At Ms */
            started_at_ms: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "current" | "complete" | "unavailable" | "skipped";
            /** Summary */
            summary: string;
        };
        /** MoneyMetric */
        MoneyMetric: {
            /** Unavailable Reason */
            unavailable_reason?: string | null;
            /**
             * Unit
             * @enum {string}
             */
            unit: "USDT" | "R" | "count" | "fraction";
            /** Value */
            value: string | null;
        };
        /** NotFoundResponse */
        NotFoundResponse: {
            /**
             * Status
             * @default not_found
             * @constant
             */
            status: "not_found";
        };
        /** OwnerConclusion */
        OwnerConclusion: {
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /**
             * Level
             * @enum {string}
             */
            level: "intervention" | "attention" | "no_action";
            /** Owner Action */
            owner_action: string | null;
            /** Summary */
            summary: string;
        };
        /** OwnerControlOperation */
        OwnerControlOperation: {
            /** Account Id */
            account_id: string;
            /** Authorization Id */
            authorization_id: string;
            /** Claimed By */
            claimed_by?: string | null;
            /** Created At Ms */
            created_at_ms: number;
            /** First Blocker */
            first_blocker?: string | null;
            /** Lease Until Ms */
            lease_until_ms?: number | null;
            /**
             * Operation Kind
             * @default flatten_all
             * @constant
             */
            operation_kind: "flatten_all";
            /** Runtime Profile Id */
            runtime_profile_id: string;
            /** Snapshot Digest */
            snapshot_digest: string;
            state: components["schemas"]["ControlOperationState"];
            /**
             * Target Ticket Ids
             * @default []
             */
            target_ticket_ids: string[];
            /** Updated At Ms */
            updated_at_ms: number;
            /** Venue Id */
            venue_id: string;
            /** Version */
            version: number;
        };
        /** OwnerOverview */
        OwnerOverview: {
            account_snapshot: components["schemas"]["AdmissionAccountSnapshot"];
            /** Active Ticket Count */
            active_ticket_count: number | null;
            /** Active Ticket Ids */
            active_ticket_ids: string[];
            /** Admitted Signal Count */
            admitted_signal_count: number;
            /** Attention Summary */
            attention_summary: string[];
            conclusion: components["schemas"]["OwnerConclusion"];
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /** Execution Incident Count */
            execution_incident_count: number | null;
            /** Observed At Ms */
            observed_at_ms: number;
            /** Rejected Signal Count */
            rejected_signal_count: number;
            /** Ticket Capacity */
            ticket_capacity: number | null;
            today_net_pnl: components["schemas"]["MoneyMetric"];
            today_net_r: components["schemas"]["MoneyMetric"];
            /** Today Signal Count */
            today_signal_count: number;
        };
        /** ProgrammaticTradeReview */
        ProgrammaticTradeReview: {
            /** Attention Items */
            attention_items: string[];
            economic_summary: components["schemas"]["ReviewEconomicSummary"];
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /**
             * Execution Classification
             * @enum {string}
             */
            execution_classification: "complete" | "recovered_incident" | "evidence_incomplete" | "in_progress" | "waiting_review";
            /** Exit Reason */
            exit_reason: string | null;
            /** Final Conclusion */
            final_conclusion: string | null;
            /**
             * Review Status
             * @enum {string}
             */
            review_status: "in_progress" | "waiting_review" | "complete" | "incomplete_evidence";
            /** Sentences */
            sentences: components["schemas"]["ReviewSentence"][];
            /** Ticket Id */
            ticket_id: string;
        };
        /** RawExchangeCommandView */
        RawExchangeCommandView: {
            /** Command Id */
            command_id: string;
            /** Command Kind */
            command_kind: string;
            /** Completed At Ms */
            completed_at_ms: number | null;
            /** Created At Ms */
            created_at_ms: number;
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /** Generation */
            generation: number;
            /** Request Payload */
            request_payload: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Result Payload */
            result_payload: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Status */
            status: string;
            /** Ticket Id */
            ticket_id: string;
        };
        /** RawIncidentView */
        RawIncidentView: {
            /** Details */
            details: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /** First Blocker */
            first_blocker: string;
            /** Incident Id */
            incident_id: string;
            /** Incident Kind */
            incident_kind: string;
            /** Opened At Ms */
            opened_at_ms: number;
            /** Resolved At Ms */
            resolved_at_ms: number | null;
            /** Status */
            status: string;
            /** Ticket Id */
            ticket_id: string;
        };
        /** RawTradeEventView */
        RawTradeEventView: {
            /**
             * Classification
             * @enum {string}
             */
            classification: "mapped" | "unmapped";
            /** Event Id */
            event_id: string;
            /** Event Type */
            event_type: string;
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /** Occurred At Ms */
            occurred_at_ms: number;
            /** Payload */
            payload: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Sequence */
            sequence: number;
            /**
             * Stage
             * @enum {string}
             */
            stage: "signal" | "admission" | "entry" | "protection" | "tp_runner" | "exit" | "reconciliation" | "review";
            /** Ticket Id */
            ticket_id: string;
        };
        /** ReviewBreakdownItem */
        ReviewBreakdownItem: {
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /** Label */
            label: string;
            /** Ticket Count */
            ticket_count: number;
        };
        /** ReviewCenterItem */
        ReviewCenterItem: {
            /** Exchange Instrument Id */
            exchange_instrument_id: string;
            /**
             * Position Side
             * @enum {string}
             */
            position_side: "long" | "short";
            review: components["schemas"]["ProgrammaticTradeReview"];
            /** Strategy Group Id */
            strategy_group_id: string;
            /** Terminal At Ms */
            terminal_at_ms: number;
            /** Ticket Id */
            ticket_id: string;
        };
        /** ReviewCenterSummary */
        ReviewCenterSummary: {
            /** Complete Review Count */
            complete_review_count: number;
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /** Execution Quality Breakdown */
            execution_quality_breakdown: components["schemas"]["ReviewBreakdownItem"][];
            /** Exit Reason Breakdown */
            exit_reason_breakdown: components["schemas"]["ReviewBreakdownItem"][];
            fees: components["schemas"]["MoneyMetric"];
            /** From Ms */
            from_ms: number;
            funding: components["schemas"]["MoneyMetric"];
            /** Incomplete Review Count */
            incomplete_review_count: number;
            /** Items */
            items: components["schemas"]["ReviewCenterItem"][];
            net_pnl: components["schemas"]["MoneyMetric"];
            net_r: components["schemas"]["MoneyMetric"];
            /** Next Cursor */
            next_cursor: string | null;
            /** Sample Count */
            sample_count: number;
            /** Strategy Group Samples */
            strategy_group_samples: components["schemas"]["StrategyGroupSampleState"][];
            /** To Ms */
            to_ms: number;
        };
        /** ReviewEconomicSummary */
        ReviewEconomicSummary: {
            fees: components["schemas"]["MoneyMetric"];
            funding: components["schemas"]["MoneyMetric"];
            gross_pnl: components["schemas"]["MoneyMetric"];
            net_pnl: components["schemas"]["MoneyMetric"];
            net_r: components["schemas"]["MoneyMetric"];
        };
        /** ReviewSentence */
        ReviewSentence: {
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /**
             * Template Id
             * @enum {string}
             */
            template_id: "execution_complete" | "execution_recovered" | "economics_complete" | "economics_incomplete" | "review_waiting" | "ticket_in_progress";
            /** Text */
            text: string;
        };
        /** ShadowOutcomeSummary */
        ShadowOutcomeSummary: {
            /** Completed At Ms */
            completed_at_ms: number | null;
            /** Completion Reason */
            completion_reason: string | null;
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /**
             * Interpretation
             * @default Observation only; this Shadow Outcome is not execution.
             * @constant
             */
            interpretation: "Observation only; this Shadow Outcome is not execution.";
            /** Mae R */
            mae_r: string | null;
            /** Mfe R */
            mfe_r: string | null;
            /** Observed Through Ms */
            observed_through_ms: number | null;
            /** Shadow Outcome Id */
            shadow_outcome_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "claimed" | "completed" | "unavailable";
        };
        /** SignalAdmissionDetail */
        SignalAdmissionDetail: {
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /** Fact Snapshots */
            fact_snapshots: components["schemas"]["SignalFactSnapshotFacts"][];
            shadow_summary: components["schemas"]["ShadowOutcomeSummary"] | null;
            signal: components["schemas"]["SignalListItem"];
            /** What Happened */
            what_happened: string;
            /** Why No Ticket */
            why_no_ticket: string | null;
        };
        /** SignalFactSnapshotFacts */
        SignalFactSnapshotFacts: {
            /** Fact Definition Id */
            fact_definition_id: string;
            /** Observed At Ms */
            observed_at_ms: number;
            /** Projection Version */
            projection_version: number;
            /**
             * Role
             * @enum {string}
             */
            role: "condition" | "protection_reference" | "identity_reference" | "lifecycle_reference" | "disable";
            /** Satisfied */
            satisfied: boolean;
            /** Signal Event Id */
            signal_event_id: string;
            /** Valid Until Ms */
            valid_until_ms: number;
            value: components["schemas"]["JsonValue"];
        };
        /** SignalListItem */
        SignalListItem: {
            /** Admission Decision Id */
            admission_decision_id: string;
            /** Binding Constraint */
            binding_constraint: string | null;
            /**
             * Decision Status
             * @enum {string}
             */
            decision_status: "admitted" | "rejected";
            /** Event Spec Id */
            event_spec_id: string;
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /** Exchange Instrument Id */
            exchange_instrument_id: string;
            /** Expires At Ms */
            expires_at_ms: number;
            /** Exposure Episode Id */
            exposure_episode_id: string;
            /** First Blocker */
            first_blocker: string | null;
            /** Occurred At Ms */
            occurred_at_ms: number;
            /**
             * Position Side
             * @enum {string}
             */
            position_side: "long" | "short";
            shadow_summary: components["schemas"]["ShadowOutcomeSummary"] | null;
            /** Signal Event Id */
            signal_event_id: string;
            /** Strategy Group Id */
            strategy_group_id: string;
            /** Strategy Version Id */
            strategy_version_id: string;
            /** Ticket Id */
            ticket_id: string | null;
        };
        /** SignalListPage */
        SignalListPage: {
            /** Items */
            items: components["schemas"]["SignalListItem"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** StrategyControlView */
        StrategyControlView: {
            configured_state: components["schemas"]["StrategyEntryState"];
            /** Control Version */
            control_version: number;
            /**
             * Effective State
             * @enum {string}
             */
            effective_state: "enabled" | "paused" | "paused_by_global";
            entry_state: components["schemas"]["StrategyEntryState"];
            /** Last Event Id */
            last_event_id: string;
            /** Reason */
            reason: string;
            /** Strategy Group Id */
            strategy_group_id: string;
            /** Updated At Ms */
            updated_at_ms: number;
        };
        /** StrategyEntryControl */
        StrategyEntryControl: {
            /** Control Version */
            control_version: number;
            entry_state: components["schemas"]["StrategyEntryState"];
            /** Last Event Id */
            last_event_id: string;
            /** Reason */
            reason: string;
            /** Strategy Group Id */
            strategy_group_id: string;
            /** Updated At Ms */
            updated_at_ms: number;
        };
        /**
         * StrategyEntryState
         * @enum {string}
         */
        StrategyEntryState: "enabled" | "paused";
        /** StrategyGroupSampleState */
        StrategyGroupSampleState: {
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /**
             * Evidence State
             * @enum {string}
             */
            evidence_state: "observe_only" | "no_evidence";
            /** Sample Count */
            sample_count: number;
            /** Strategy Group Id */
            strategy_group_id: string;
        };
        /** TradeCausalityDetail */
        TradeCausalityDetail: {
            /** Annotations */
            annotations: components["schemas"]["ChartAnnotation"][];
            /**
             * Current Stage
             * @enum {string}
             */
            current_stage: "signal" | "admission" | "entry" | "protection" | "tp_runner" | "exit" | "reconciliation" | "review";
            /** Current Stage Summary */
            current_stage_summary: string;
            /** Event Evidence */
            event_evidence: components["schemas"]["EvidenceRef"][];
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            exit_reason: components["schemas"]["CausalityExitReason"] | null;
            /** Incident Evidence */
            incident_evidence: components["schemas"]["EvidenceRef"][];
            /** Order Evidence */
            order_evidence: components["schemas"]["EvidenceRef"][];
            /** Raw Commands */
            raw_commands: components["schemas"]["RawExchangeCommandView"][];
            /** Raw Events */
            raw_events: components["schemas"]["RawTradeEventView"][];
            /** Raw Incidents */
            raw_incidents: components["schemas"]["RawIncidentView"][];
            /** Review Evidence */
            review_evidence: components["schemas"]["EvidenceRef"][];
            /** Settlement Evidence */
            settlement_evidence: components["schemas"]["EvidenceRef"][];
            /** Signal Evidence */
            signal_evidence: components["schemas"]["EvidenceRef"][];
            /** Stages */
            stages: components["schemas"]["LifecycleStageView"][];
            trade: components["schemas"]["TradeListItem"];
        };
        /** TradeListItem */
        TradeListItem: {
            /** Aggregate Status */
            aggregate_status: string;
            /** Attention Items */
            attention_items: string[];
            /** Completed Stage Count */
            completed_stage_count: number;
            /** Economics Completeness */
            economics_completeness: ("complete" | "funding_unavailable" | "external_exit_unavailable") | null;
            /** Event Spec Id */
            event_spec_id: string;
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /** Exchange Instrument Id */
            exchange_instrument_id: string;
            /** Exit Reason */
            exit_reason: string | null;
            /** Exit Reason Unavailable Reason */
            exit_reason_unavailable_reason: string | null;
            fees: components["schemas"]["MoneyMetric"];
            funding: components["schemas"]["MoneyMetric"];
            gross_pnl: components["schemas"]["MoneyMetric"];
            /** Issued At Ms */
            issued_at_ms: number;
            /**
             * Lifecycle Stage
             * @enum {string}
             */
            lifecycle_stage: "signal" | "admission" | "entry" | "protection" | "tp_runner" | "exit" | "reconciliation" | "review";
            net_pnl: components["schemas"]["MoneyMetric"];
            net_r: components["schemas"]["MoneyMetric"];
            /**
             * Position Side
             * @enum {string}
             */
            position_side: "long" | "short";
            /** Review Id */
            review_id: string | null;
            /** Review Revision */
            review_revision: number | null;
            /** Strategy Group Id */
            strategy_group_id: string;
            /** Terminal At Ms */
            terminal_at_ms: number | null;
            /** Ticket Id */
            ticket_id: string;
            /** Ticket Status */
            ticket_status: string;
            /**
             * Total Stage Count
             * @constant
             */
            total_stage_count: 8;
        };
        /** TradeListPage */
        TradeListPage: {
            /** Items */
            items: components["schemas"]["TradeListItem"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** _LoginRequest */
        _LoginRequest: {
            /** Password */
            password: string;
            /** Totp Code */
            totp_code: string;
            /** Username */
            username: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_owner_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["_LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_owner_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    session_api_owner_v1_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    read_control_events_api_owner_v1_control_events_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlEventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_control_operation_api_owner_v1_control_operations__authorization_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                authorization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerControlOperation"] | components["schemas"]["NotFoundResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_controls_api_owner_v1_controls_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlsResponse"];
                };
            };
        };
    };
    pause_global_entry_api_owner_v1_controls_entry_pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlWriteBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_global_entry_api_owner_v1_controls_entry_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlWriteBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    flatten_submit_api_owner_v1_controls_exposure_flatten_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlattenBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerControlOperation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    flatten_preview_api_owner_v1_controls_exposure_flatten_all_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyControlBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlattenPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_strategy_api_owner_v1_controls_strategies__strategy_group_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlWriteBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyEntryControl"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_strategy_api_owner_v1_controls_strategies__strategy_group_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlWriteBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyEntryControl"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    candles_api_owner_v1_market_candles_get: {
        parameters: {
            query: {
                exchange_instrument_id: string;
                timeframe: "15m" | "1h";
                closed_at_ms: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_CandleSeries_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_owner_v1_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_OwnerOverview_"];
                };
            };
        };
    };
    review_center_api_owner_v1_review_get: {
        parameters: {
            query?: {
                from_ms?: number | null;
                to_ms?: number | null;
                limit?: number;
                cursor?: string | null;
                review_status?: ("in_progress" | "waiting_for_settlement" | "waiting_for_review" | "complete" | "incomplete_evidence") | null;
                strategy_group_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_ReviewCenterSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signals_api_owner_v1_signals_get: {
        parameters: {
            query?: {
                from_ms?: number | null;
                to_ms?: number | null;
                limit?: number;
                cursor?: string | null;
                decision_status?: ("admitted" | "rejected") | null;
                strategy_group_id?: string | null;
                exchange_instrument_id?: string | null;
                position_side?: ("long" | "short") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_SignalListPage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signal_detail_api_owner_v1_signals__signal_event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signal_event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_SignalAdmissionDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tickets_api_owner_v1_tickets_get: {
        parameters: {
            query?: {
                from_ms?: number | null;
                to_ms?: number | null;
                limit?: number;
                cursor?: string | null;
                aggregate_status?: string | null;
                strategy_group_id?: string | null;
                exchange_instrument_id?: string | null;
                position_side?: ("long" | "short") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_TradeListPage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ticket_causality_api_owner_v1_tickets__ticket_id__causality_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_TradeCausalityDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
