strategy:
  atr:
    enabled: true
    min_atr_ratio: 0.5
    period: 14
  ema:
    period: 60
  mtf:
    ema_period: 60
    mapping:
      15m: 1h
      1h: 4h
      4h: 1d
      1d: 1w
  pinbar:
    body_position_tolerance: 0.3
    max_body_ratio: 0.3
    min_wick_ratio: 0.6
risk:
  max_leverage: 10
  max_loss_percent: 0.02
