exchange:
  name: binance
  api_key: zsJTNLPRwBSYPMVPz5sHmXnsmtyQv6D3SYRSD628DAiQclKSCHwqIgDLwaDfiDS8
  api_secret: DIN5M3SJ0lXoNJfvCAbIIMLfrQ1eiVqMRThOedUG2p2lCg0eWlc2OQJ16ySLg391
  testnet: false
user_symbols: []
timeframes:
- 15m
- 1h
active_strategies:
- id: ''
  name: test_pinbar
  logic_tree:
    type: trigger
    id: trigger_0
    config:
      id: ''
      type: pinbar
      enabled: true
      params: {}
  triggers:
  - id: ''
    type: pinbar
    enabled: true
    params: {}
  trigger_logic: OR
  trigger:
    id: ''
    type: pinbar
    enabled: true
    params: {}
  filters: []
  filter_logic: AND
  is_global: true
  apply_to: []
strategy: null
risk:
  max_loss_percent: '0.01'
  max_leverage: 125
  max_total_exposure: '0.8'
asset_polling:
  interval_seconds: 60
notification:
  channels:
  - type: feishu
    webhook_url: https://open.feishu.cn/open-apis/bot/v2/hook/14797747-0403-4455-a7fe-f6b69cf0ef04
