#!/usr/bin/env python3
"""检查 max_drawdown 计算逻辑"""
import sys
from pathlib import Path

project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

print("=" * 80)
print("max_drawdown 计算逻辑检查")
print("=" * 80)

print("\n【1. 相关代码位置】")
print("-" * 80)
print("文件: src/application/backtester.py")
print()
print("第 1543 行：equity_curve 初始化")
print("  equity_curve: List[Tuple[int, Decimal]] = []  # [(timestamp_ms, total_balance), ...]")
print()
print("第 1828 行：equity_curve 记录")
print("  equity_curve.append((kline.timestamp, account.total_balance))")
print()
print("第 1962-1970 行：max_drawdown 计算")
print("  max_drawdown = Decimal('0')")
print("  peak = initial_balance")
print("  for _, equity in equity_curve:")
print("      if equity > peak:")
print("          peak = equity")
print("      if peak > 0:")
print("          drawdown = (peak - equity) / peak")
print("          if drawdown > max_drawdown:")
print("              max_drawdown = drawdown")
print()
print("第 390 行：未实现盈亏设置")
print("  unrealized_pnl=Decimal('0'),  # 回测中无浮动盈亏概念")
print()
print("第 2190 行：账户余额更新（平仓时）")
print("  account.total_balance += close_pnl")

print("\n【2. max_drawdown 当前真实口径】")
print("-" * 80)
print("✅ 基于 equity_curve 计算")
print("✅ equity_curve 只记录 account.total_balance")
print("✅ account.total_balance 只包含：")
print("   - 初始资金")
print("   - 已实现盈亏（平仓时更新）")
print("   - 已扣除的手续费")
print("   - 已扣除的滑点")
print("   - 已扣除的 funding cost")
print()
print("❌ 不包含：")
print("   - 持仓过程中的未实现盈亏")
print("   - 持仓过程中的浮动亏损")

print("\n【3. 是否包含浮动亏损】")
print("-" * 80)
print("❌ 不包含浮动亏损")
print()
print("证据：")
print("1. 代码注释明确说明：'回测中无浮动盈亏概念'")
print("2. equity_curve 只在以下时机更新：")
print("   - 每根 K 线结束时（第 1828 行）")
print("   - 但此时 account.total_balance 不包含未实现盈亏")
print("3. account.total_balance 只在平仓时更新（第 2190 行）")
print("   - 平仓时才将 close_pnl 计入余额")

print("\n【4. intratrade drawdown 示例】")
print("-" * 80)
print("假设一笔持仓：")
print("  - 入场价: 100")
print("  - 止损: 95（风险 5%）")
print("  - 持仓过程中价格跌到 96（浮亏 4%）")
print("  - 最后价格涨到 110，平仓盈利 10%")
print()
print("当前 max_drawdown 计算结果：")
print("  ✅ 会记录平仓后的盈利（+10%）")
print("  ❌ 不会记录持仓过程中的浮亏（-4%）")
print("  ❌ max_drawdown = 0%（因为 equity_curve 只在平仓时更新）")
print()
print("真实风险：")
print("  ✅ 这笔持仓中途确实承受了 4% 的浮亏")
print("  ✅ 真实 max_drawdown 应该是 4%")
print("  ❌ 但当前计算结果为 0%")

print("\n【5. 结论】")
print("=" * 80)
print("❌ 当前回撤值不可信")
print()
print("原因：")
print("1. max_drawdown 只反映'已实现盈亏曲线'的回撤")
print("2. 不反映持仓过程中的真实风险（浮动亏损）")
print("3. 会严重低估真实风险")
print()
print("影响：")
print("- 如果策略经常'先大幅浮亏，最后才平仓盈利'")
print("- 当前 max_drawdown 会严重低估风险")
print("- 可能导致对策略风险控制能力的错误判断")
print()
print("建议：")
print("- 需要在每根 K 线结束时，计算持仓的未实现盈亏")
print("- 将未实现盈亏计入 equity_curve")
print("- 这样才能反映真实的 intratrade drawdown")
print("=" * 80)
