"""
Research artifact helpers.

This module is deliberately small and pure: it only provides metadata helpers
for reports/artifacts generated by backtests/optuna studies.
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Optional


@dataclass(frozen=True)
class GitMetadata:
    commit: Optional[str]
    branch: Optional[str]
    is_dirty: Optional[bool]

    def to_dict(self) -> dict[str, object]:
        return {
            "commit": self.commit,
            "branch": self.branch,
            "is_dirty": self.is_dirty,
        }


def _run_git(args: list[str], *, cwd: Path) -> Optional[str]:
    try:
        output = subprocess.check_output(
            ["git", *args],
            cwd=str(cwd),
            stderr=subprocess.DEVNULL,
            timeout=2,
        )
    except Exception:
        return None
    value = output.decode("utf-8", errors="replace").strip()
    return value or None


def get_git_metadata(repo_root: Path) -> GitMetadata:
    commit = _run_git(["rev-parse", "HEAD"], cwd=repo_root)
    branch = _run_git(["rev-parse", "--abbrev-ref", "HEAD"], cwd=repo_root)
    status = _run_git(["status", "--porcelain"], cwd=repo_root)
    is_dirty = None if status is None else bool(status.strip())
    return GitMetadata(commit=commit, branch=branch, is_dirty=is_dirty)

